---
name: automerge
on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  check-mergeability:
     if: ${{ github.event.workflow_run.conclusion == 'success' && github.actor == 'nsmbot' }}
     uses: NikitaSkrynnik/.github/.github/workflows/check-mergeability.yaml@cmd-workflows
     secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}

  automerge:
    needs: [check-mergeability]
    if: ${{ needs.check-mergeability.result == 'success' }}
    uses: NikitaSkrynnik/.github/.github/workflows/automerge.yaml@cmd-workflows

  resolve_conflicts:
    needs: [check-mergeability]
    if: ${{ always() && needs.check-mergeability.result == 'failure' && needs.check-mergeability.outputs.pr_branch_ref != '' }}
    uses: NikitaSkrynnik/.github/.github/workflows/check-mergeability.yaml@cmd-workflows
    with:
      pr_branch_ref: ${{ needs.check-mergeability.outputs.pr_branch_ref }}
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}
