---
name: Pull Request on update/* Branch Push
on:
  push:
    branches:
      - update/**
jobs:
  auto-pull-request:
    uses: NikitaSkrynnik/.github/.github/workflows/pr-for-updates.yaml@cmd-workflows
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
