---
name: Release

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
    branches:
      - release/*
jobs:
  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    outputs:
      tag: ${{ steps.get-tag-step.outputs.tag }}
    steps:
      - name: Get tag
        run: |
          branch=${{github.event.workflow_run.head_branch}}
          echo tag=${branch#release/} >> $GITHUB_OUTPUT
        id: get-tag-step

  update-deployments-k8s:
    name: Update deployments-k8s
    needs: [get-tag]
    if: ${{ github.repository != 'networkservicemesh/cmd-template' }}
    uses: NikitaSkrynnik/.github/.github/workflows/release-deployments.yaml@release-rework-test
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
    secrets:
      token: ${{ secrets.MY_TOKEN }}
