---
name: Release

on:
  workflow_run:
    types:
      - completed
    workflows:
      - "ci"
jobs:
  get-tag:
    name: Get tag
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' && contains(github.event.workflow_run.head_branch, 'release/') }}
    outputs:
      tag: ${{ steps.get-tag-step.outputs.tag }}
    steps:
      - name: Get tag
        run: |
          branch=${{github.event.workflow_run.head_branch}}
          echo '::set-output name=tag::'${branch#release/}
        id: get-tag-step

  check-gomod-deps:
    needs: get-tag
    uses: NikitaSkrynnik/.github/.github/workflows/check-gomod-deps.yaml@cmd-workflows
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
  
  create-release:
    needs: [get-tag, check-gomod-deps]
    uses: NikitaSkrynnik/.github/.github/workflows/release.yaml@cmd-workflows
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}

  docker:
    needs: [get-tag, check-gomod-deps]
    uses: NikitaSkrynnik/.github/.github/workflows/release.yaml@cmd-workflows
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
    
  check-branch:
    name: Check release branch in deployments-k8s
    needs: [get-tag, create-release]
    uses: NikitaSkrynnik/.github/.github/workflows/check-release-branch.yaml@cmd-workflows
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}

  update-deployments-k8s:
    name: Update deployments-k8s
    needs: [get-tag, check-branch]
    if: ${{ github.repository != 'networkservicemesh/cmd-template' }}
    uses: NikitaSkrynnik/.github/.github/workflows/release-deployments.yaml@cmd-workflows
    with:
      tag: ${{ needs.get-tag.outputs.tag }}
    secrets:
      token: ${{ secrets.NSM_BOT_GITHUB_TOKEN }}

